sonar.projectKey=Lealzap_jazz-influencia-ab
sonar.organization=lealzap
sonar.projectName=Jazz Influência AB
sonar.projectVersion=1.0.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,cypress/**,.git/**,dist/**,build/**
sonar.test.inclusions=cypress/**/*.cy.js,**/*.test.js

sonar.qualitygate.wait=true
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.projectDescription=Projeto frontend e DevOps - Influência do Jazz no R&B