sonar.projectKey=jazz-influencia-ab
sonar.projectName=Jazz Influência AB
sonar.projectVersion=1.0

sonar.sources=.
sonar.sourceEncoding=UTF-8

sonar.exclusions=node_modules/**,dist/**,build/**,.git/**