name: SonarCloud

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verificar se SONAR_TOKEN existe
        run: |
          if [ -z "${{ secrets.SONAR_TOKEN }}" ]; then
            echo "SONAR_TOKEN está vazio ou não existe"
            exit 1
          else
            echo "SONAR_TOKEN existe"
          fi

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=Lealzap_jazz-influencia-ab
            -Dsonar.organization=lealzap
            -Dsonar.host.url=https://sonarcloud.io